@baseUrl = http://localhost:3333

# @name register
POST {{baseUrl}}/register
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@example.com",
  "password": "johnjohn"
}

###

# @name authenticate
POST {{baseUrl}}/auth
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "johnjohn"
}

###

# @name profile
GET {{baseUrl}}/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciIsInN1YiI6IjgwYTc0MTViLWVlNjEtNGI5MC1hYzllLTkyOWYyMWNjM2U5OSIsImlhdCI6MTcwODAxMDc4NiwiZXhwIjoxNzA4MDExMzg2fQ.JdogDQoMzzXSeSnWeBTRL8WWcjKfcHe6DcYVqeNjUUc

###

# @name forget_password
POST {{baseUrl}}/forget_password
Content-Type: application/json

{
  "email": "john@example.com"
}

###

# @name restore
PATCH {{baseUrl}}/restore-password?email=john@example.com
Content-Type: application/json

{
  "password": "john_node2"
}

###

# @name restore
GET {{baseUrl}}/user?email=john@example.com

###

# @name fetch_notes
GET {{baseUrl}}/notes?page=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciIsInN1YiI6IjgwYTc0MTViLWVlNjEtNGI5MC1hYzllLTkyOWYyMWNjM2U5OSIsImlhdCI6MTcwODAxMDc4NiwiZXhwIjoxNzA4MDExMzg2fQ.JdogDQoMzzXSeSnWeBTRL8WWcjKfcHe6DcYVqeNjUUc

###

# @name create_note
POST {{baseUrl}}/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciIsInN1YiI6IjgwYTc0MTViLWVlNjEtNGI5MC1hYzllLTkyOWYyMWNjM2U5OSIsImlhdCI6MTcwODAxMDc4NiwiZXhwIjoxNzA4MDExMzg2fQ.JdogDQoMzzXSeSnWeBTRL8WWcjKfcHe6DcYVqeNjUUc

{
  "content": "new note 3"
}