@baseUrl = http://localhost:3333

# @name register
POST {{baseUrl}}/register
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@example.com",
  "password": "johnjohn"
}

###

# @name authenticate
POST {{baseUrl}}/auth
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "johnjohn"
}

###

# @name profile
GET {{baseUrl}}/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9obiBEb2UiLCJlbWFpbCI6ImpvaG5AZXhhbXBsZS5jb20iLCJzdWIiOiJiODE2MWU2Mi05N2JhLTRkNTMtODUxZC1iYjVjNThiZGRjNDUiLCJpYXQiOjE3MDc4NjY3MTMsImV4cCI6MTcwNzg2NzMxM30.vah6Jqp1qbUupokahswl70w3F8XVirJEUG_UgIqYBoc

###

# @name forget_password
POST {{baseUrl}}/forget_password
Content-Type: application/json

{
  "email": "john@example.com"
}

###

# @name restore
PATCH {{baseUrl}}/restore-password?email=john@example.com
Content-Type: application/json

{
  "password": "john_node2"
}

###

# @name restore
GET {{baseUrl}}/user?email=john@example.com